import assert from "node:assert/strict"
import { readFileSync } from "node:fs"
import test from "node:test"

const source = (path) => readFileSync(new URL(`../${path}`, import.meta.url), "utf8")
const visibleJsxText = (value) => [...value.matchAll(/>([^<{]+)</g)].map((match) => match[1]).join(" ")

test("MCSW Jobs exposes the compact mobile hierarchy and keeps advanced tools under Menu", () => {
  // C7 flipped the shell to the board language: the /ops home is a redirect to
  // /board, the weighted indexes are archived, and the shared chrome is styled
  // by ops-shell.css. The board itself carries the tracker hierarchy now.
  const header = source("app/ops/ops-header.tsx")
  const layout = source("app/ops/layout.tsx")
  const more = source("app/ops/more-menu.tsx")
  const dock = source("app/ops/shop-dock.tsx")
  const home = source("app/ops/page.tsx")
  const intake = source("app/ops/intake/inline-job-intake.tsx")
  const board = source("app/board/board.tsx")
  const css = source("app/ops/ops-shell.css")

  assert.match(header, /MCSW Jobs/)
  assert.match(header, /firstName/)
  assert.match(header, /<MoreMenu/)
  assert.match(more, /aria-label=\{open \? "Close menu" : "Open menu"\}/)
  assert.match(more, /<MenuIcon/)
  assert.match(more, /<CloseIcon/)
  assert.doesNotMatch(header, /<strong>Jobs<\/strong>/)
  assert.doesNotMatch(layout, /ShopDock/)
  for (const label of ["Job Control", "New Job", "Promises", "Search Jobs", "Install MCSW Jobs", "Settings", "Sign out"]) {
    assert.match(more, new RegExp(label))
  }
  assert.match(dock, /Ask Jobs/)
  assert.match(dock, /Morning Brief/)
  assert.match(home, /redirect\("\/board"\)/)
  assert.match(board, /Showing \$\{board\.items\.length\} of \$\{board\.resultTotal\}/)
  assert.match(intake, /useState<IntakeSource>\(initialSource\)/)
  assert.match(intake, /source === "phone-in" \? "Phone call" : "Walk-in"/)
  assert.match(intake, /switchSource\(source === "phone-in" \? "walk-in" : "phone-in"\)/)
  assert.match(intake, /Name or company/)
  assert.match(intake, /<span>Needs<\/span>/)
  assert.match(intake, /moreOpen \? "Close details" : "More details"/)
  assert.match(intake, /Job saved/)
  assert.match(intake, /Open Job/)
  assert.match(intake, /undoInlineJobAction/)
  assert.match(css, /\.ops-frame\s*\{[^}]*width:\s*min\(100%, 92rem\)/s)
  assert.match(css, /min-height:\s*44px/)
  assert.match(
    css,
    /\.ops-more-trigger\[aria-expanded="true"\]\s*\{[^}]*position:\s*fixed;[^}]*top:\s*max\([^;]*env\(safe-area-inset-top[^;]*;[^}]*right:\s*max\([^;]*env\(safe-area-inset-right[^;]*;/s,
  )
})

test("mobile side effects use centered scroll-safe controls with busy-state protection", () => {
  const safe = source("app/ops/safe-action-controls.tsx")
  const intake = source("app/ops/intake/inline-job-intake.tsx")
  const updates = source("app/ops/wire-strip.tsx")
  const css = source("app/globals.css")
  assert.match(safe, /safeActionMovement/)
  assert.match(safe, /onPointerMove=\{press\.pointerMove\}/)
  assert.match(safe, /onPointerCancel=\{press\.pointerCancel\}/)
  assert.match(safe, /if \(press\.consumeCanceled\(\)\)/)
  assert.match(safe, /disabled=\{pending \|\| props\.disabled\}/)
  assert.match(safe, /if \(busy \|\| disabled\) return/)
  assert.match(intake, /import \{ SafeActionButton, SafeSubmitButton \}/)
  assert.match(intake, /<SafeSubmitButton[^>]*>Save Job<\/SafeSubmitButton>/)
  assert.match(
    intake,
    /changeDisposition\("dismiss"\)[\s\S]{0,120}>Not a job<\/SafeActionButton>/,
  )
  assert.match(updates, /SafeActionButton/)
  assert.match(updates, /SafeSubmitButton/)
  assert.match(updates, /if \(working !== null\) return/)
  assert.match(updates, /All Updates/)
  assert.match(updates, /Search updates/)
  assert.match(css, /\.ops-row-actions\s*\{[^}]*justify-content:\s*center[^}]*padding:\s*\.3rem clamp\(1\.5rem, 7vw, 5rem\)/s)
  assert.match(css, /\.ops-safe-action\s*\{\s*touch-action:\s*pan-y;/)
})

test("mobile quick replies leave a separate usable free-form composer", () => {
  const reply = source("app/ops/leads/[id]/spike-reply.tsx")
  const css = source("app/ops/leads/[id]/job.css")

  assert.match(reply, /aria-label=\{channel === "email" \? "Email reply" : "Text reply"\}/)
  assert.match(reply, /aria-label="Quick replies"/)
  assert.match(reply, /onClick=\{\(\) => setBody\(copy\)\}/)
  assert.match(
    css,
    /\.job-page \.ops-spike-reply\s*\{[^}]*grid-template-columns:\s*auto minmax\(0, 1fr\) auto;[^}]*\}[\s\S]*?\.job-page \.ops-spike-reply > input\[name="body"\]\s*\{[^}]*grid-column:\s*2;[^}]*grid-row:\s*2;[^}]*\}[\s\S]*?\.job-page \.ops-spike-reply > button\[type="submit"\]\s*\{[^}]*grid-column:\s*3;[^}]*grid-row:\s*2;[^}]*\}/,
  )
  assert.match(
    css,
    /@media \(max-width: 40rem\) \{[\s\S]*?\.job-page \.ops-spike-reply\s*\{[^}]*grid-template-columns:\s*minmax\(0, 1fr\);[^}]*\}[\s\S]*?\.job-page \.ops-spike-reply > input\[name="body"\]\s*\{[^}]*grid-column:\s*1;[^}]*grid-row:\s*4;[^}]*\}[\s\S]*?\.job-page \.ops-spike-reply > button\[type="submit"\]\s*\{[^}]*grid-column:\s*1;[^}]*grid-row:\s*5;[^}]*\}/,
  )
})

test("Swipe to Finish is deliberate, scroll-canceling, single-submit, accessible, and undoable", () => {
  const done = source("app/ops/leads/[id]/done-stamp.tsx")
  const actions = source("app/ops/actions.ts")
  assert.match(done, /swipeFinishDecision/)
  assert.match(done, /decision\.outcome === "cancel"/)
  assert.match(done, /decision\.outcome === "submit"\) finish\(\)/)
  assert.match(done, /submittedRef\.current = true/)
  assert.match(done, /if \(completed \|\| submitting \|\| submittedRef\.current\) return/)
  assert.match(done, /Press again to finish/)
  assert.match(done, /Keyboard users press Enter twice/)
  assert.match(done, /const remaining = undoUntil \? new Date\(undoUntil\)\.getTime\(\) - Date\.now\(\) : 0/)
  assert.match(done, /setTimeout\(\(\) => setUndoExpired\(remaining <= 0\), 0\)/)
  assert.match(done, /setTimeout\(\(\) => setUndoExpired\(true\), remaining\)/)
  assert.match(done, /Undo finish \(10 sec\)/)
  assert.match(done, /submittedRef\.current = false/)
  assert.match(done, /setSubmitting\(false\)/)
  assert.match(actions, /WHERE id = \$\{leadId\}::bigint AND completed_at IS NULL/)
  assert.match(actions, /e\.occurred_at >= now\(\) - interval '10 seconds'/)
})

test("work orders use the requested phone-first order and one condensed paged record", () => {
  const page = source("app/ops/leads/[id]/page.tsx")
  const events = source("lib/events.ts")
  assert.match(page, /Calls &amp; Messages/)
  assert.match(page, /Recent Activity/)
  assert.match(page, /Full Record/)
  assert.match(page, /\.reverse\(\)\.slice\(0, 3\)/)
  assert.match(page, /listLeadEventPage\(leadId, requestedActivityPage, 25, operator\.role\)/)
  assert.match(events, /const pageSize = Math\.min\(Math\.max\(limit, 1\), 25\)/)
  assert.match(events, /OWNER_ONLY_EVENT_KINDS/)
  assert.match(events, /\$\{role\}::text = 'owner'/)
  assert.match(events, /ORDER BY e\.occurred_at DESC, e\.id DESC\s+LIMIT \$\{pageSize\}::int OFFSET \$\{offset\}::int/s)
  const summary = page.indexOf('aria-label="Job summary"')
  const promises = page.indexOf('aria-label="Job promises"')
  const messages = page.indexOf('aria-label="Customer thread"')
  const details = page.indexOf('className="card job-details"')
  const done = page.indexOf("<DoneStamp")
  const history = page.indexOf('aria-label="Recent activity"')
  assert.ok(summary >= 0 && summary < promises && promises < messages, "Summary, promises, and messages must follow the approved DOM order")
  assert.ok(messages < details && details < done && done < history, "Customer work, details, finish, and history must follow the approved DOM order")
})

test("Customer Page uploads persist intent first, enforce quotas, converge idempotently, and recover", () => {
  const client = source("app/j/[token]/glass-upload.tsx")
  const authorize = source("app/api/glass/upload/route.ts")
  const finalize = source("app/api/glass/upload/finalize/route.ts")
  const uploads = source("lib/glass-uploads.ts")
  const recovery = source("lib/recovery-sweep.ts")
  const migration = source("scripts/migrate.mjs")

  assert.ok(client.indexOf("const intent = await fileIntent(item)") < client.indexOf("await upload(intent.pathname"))
  assert.match(client, /access: "private"/)
  assert.match(client, /multipart: true/)
  assert.match(client, /Uploading/)
  assert.match(client, /Filing/)
  assert.match(client, /Added/)
  assert.match(client, /Retry/)
  assert.match(authorize, /handleUpload/)
  assert.match(authorize, /onBeforeGenerateToken/)
  assert.match(authorize, /onUploadCompleted/)
  assert.match(authorize, /addRandomSuffix: false/)
  assert.match(finalize, /\^\[a-f0-9\]\{64\}\$/)
  assert.match(uploads, /GLASS_UPLOAD_MAX_FILES_PER_BATCH = 10/)
  assert.match(uploads, /GLASS_UPLOAD_MAX_FILE_BYTES = 20 \* 1024 \* 1024/)
  assert.match(uploads, /GLASS_UPLOAD_MAX_FILES_PER_DAY = 30/)
  assert.match(uploads, /GLASS_UPLOAD_MAX_BYTES_PER_DAY = 100 \* 1024 \* 1024/)
  assert.match(uploads, /pg_advisory_xact_lock\(hashtext\(token_hash\)\)/)
  assert.match(uploads, /const blob = await head\(upload\.pathname/)
  assert.match(uploads, /blob\.pathname !== upload\.pathname/)
  assert.match(uploads, /if \(upload\.status === "stored"\) return upload/)
  assert.match(uploads, /ON CONFLICT \(twilio_sid\) DO UPDATE SET/)
  assert.match(uploads, /if \(!upload\.is_test && upload\.event_id\)/)
  assert.match(uploads, /if \(notifyGate\[0\]\) await notifyAll/)
  assert.match(uploads, /export async function reconcileGlassUploads/)
  assert.match(recovery, /reconcileGlassUploads\(\)/)
  assert.match(migration, /CREATE TABLE IF NOT EXISTS glass_uploads/)
  for (const status of ["pending", "uploading", "uploaded", "projecting", "stored", "failed", "unknown"]) {
    assert.match(migration, new RegExp(`'${status}'`))
  }
})

test("Customer Page attachment delivery rechecks the bearer and never renders active documents", () => {
  const attachment = source("app/api/glass/attachment/route.ts")
  const uploads = source("lib/glass-uploads.ts")
  const glass = source("lib/glass.ts")
  const safety = source("lib/media-safety.ts")
  assert.match(uploads, /getGlassJob\(token\)/)
  assert.match(uploads, /job\.status === "closed"/)
  assert.match(uploads, /status = 'stored'/)
  assert.match(glass, /g\.revoked_at IS NULL/)
  assert.match(attachment, /get\(upload\.pathname, \{ access: "private" \}\)/)
  assert.match(attachment, /inline \? "inline" : "attachment"/)
  assert.match(attachment, /X-Content-Type-Options": "nosniff"/)
  assert.match(attachment, /Content-Security-Policy": "sandbox; default-src 'none'"/)
  assert.match(safety, /image\/jpeg/)
  assert.doesNotMatch(safety, /image\/svg\+xml/)
})

test("uploads feed Calls and Messages plus Needs Attention without alerting test jobs", () => {
  const uploads = source("lib/glass-uploads.ts")
  const needs = source("lib/ops-data.ts")
  assert.match(uploads, /Customer added photos or files/)
  assert.match(uploads, /'glass\.uploaded'/)
  assert.match(uploads, /url: `\/ops\/leads\/\$\{upload\.lead_id\}#spike`/)
  assert.match(uploads, /if \(!upload\.is_test && upload\.event_id\)/)
  assert.match(uploads, /if \(notifyGate\[0\]\) await notifyAll/)
  assert.match(needs, /'glass\.uploaded'/)
  assert.match(needs, /WHEN 'glass\.uploaded' THEN 'customer files waiting'/)
  assert.match(needs, /l\.is_test = false/)
})

test("text consent is immutable, explicit, keyword-aware, and enforced before every send", () => {
  const contact = source("components/mainstreet-contact.tsx")
  const quote = source("app/api/quote/route.ts")
  const consent = source("lib/messaging-consent.ts")
  const invariants = source("lib/shop-brain-invariants.mjs")
  const sms = source("app/api/twilio/sms/route.ts")
  const messages = source("lib/messages.ts")
  const migration = source("scripts/migrate.mjs")
  const privacy = source("app/privacy/page.tsx")
  const terms = source("app/terms/page.tsx")
  const ownerConsent = source("app/ops/leads/[id]/page.tsx")

  assert.match(contact, /Text me about this job/)
  assert.match(contact, /privacy policy/)
  assert.match(contact, /terms/)
  assert.match(contact, /By checking this box, you agree to receive recurring customer-care and job-update text messages from Music City Specialty Welding about this request/)
  for (const disclosure of [contact, privacy, terms, ownerConsent]) {
    assert.match(disclosure, /customer-care and job-update text messages from Music City Specialty Welding/)
    assert.match(disclosure, /Message frequency varies/)
    assert.match(disclosure, /Message and data rates may apply/)
    assert.match(disclosure, /STOP to unsubscribe/)
    assert.match(disclosure, /HELP for help/)
    assert.match(disclosure, /Consent is optional and is not a condition of purchase/)
  }
  assert.match(ownerConsent, /Use this only after the customer clearly says yes/)
  assert.match(quote, /const textConsent = .* === "yes"/)
  assert.match(quote, /if \(textConsent && !isTest\)/)
  assert.doesNotMatch(quote, /recordMessagingConsent/)
  assert.match(quote, /webTextConsent:/)
  assert.match(quote, /Lead and text-consent persistence error/)
  assert.match(quote, /couldn't confirm the saved text permission/)
  assert.match(consent, /"web" \| "inbound-message" \| "verbal-operator" \| "START" \| "STOP" \| "HELP"/)
  assert.match(consent, /STOP: "revoked"/)
  assert.match(consent, /START: "granted"/)
  assert.match(consent, /HELP: "recorded"/)
  assert.match(consent, /classifyTwilioConsentKeyword/)
  assert.match(invariants, /const exactBody = String\(body \?\? ""\)\.trim\(\)\.toUpperCase\(\)/)
  assert.match(consent, /source IN \('STOP', 'START'\)/)
  assert.match(consent, /WHEN \(SELECT source FROM keyword_state\) = 'STOP' THEN 'revoked'/)
  assert.match(consent, /ON CONFLICT \(external_id\) DO NOTHING/)
  assert.match(sms, /OptOutType/)
  assert.match(sms, /(?:consentKeyword \|\| systemSms)\s*\? await \(async \(\) =>/)
  assert.match(sms, /findPersonByPhone\(from\)/)
  assert.match(sms, /if \(!isConfiguredTwilioNumber\(to\)\)/)
  assert.match(sms, /if \(eventId && !consentKeyword/)
  assert.match(sms, /return twiml\(""\)/)
  assert.match(messages, /customerSmsAllowed\(to\)/)
  assert.match(messages, /Texting is blocked until this customer opts in/)
  assert.match(migration, /CREATE TABLE IF NOT EXISTS messaging_consents/)
  assert.match(migration, /messaging_consents_source_check/)
  assert.match(migration, /messaging_consents_append_only/)
  assert.match(migration, /BEFORE UPDATE OR DELETE ON messaging_consents/)
  assert.match(privacy, /append-only record/)
  assert.match(privacy, /do not sell or share mobile opt-in information/)
  assert.match(terms, /Optional Job Texts/)
  assert.match(terms, /A STOP request overrides earlier permission until a later START/)
})

test("Twilio webhooks survive an outbound pause and reconcile provider-first callbacks", () => {
  const twilio = source("lib/twilio.ts")
  const sms = source("app/api/twilio/sms/route.ts")
  const status = source("app/api/twilio/sms-status/route.ts")
  const messages = source("lib/messages.ts")
  const call = source("app/api/ops/call/route.ts")
  const outboundStatus = source("app/api/twilio/outbound-status/route.ts")
  const voice = source("app/api/twilio/voice/route.ts")
  const fallback = source("app/api/twilio/fallback/route.ts")
  const recording = source("app/api/twilio/recording/route.ts")
  const outboundConnect = source("app/api/twilio/outbound-connect/route.ts")
  const callTranscription = source("lib/call-transcription.ts")
  const health = source("app/api/health/route.ts")
  const leads = source("lib/leads.ts")

  assert.match(twilio, /export function twilioSmsWebhookConfigured\(\)/)
  assert.match(twilio, /twilioSmsWebhookConfigured\(\)[\s\S]{0,180}TWILIO_SMS_ENABLED/)
  assert.match(twilio, /parsed\.protocol !== "https:"/)
  for (const rejectedUrlPart of ["parsed.username", "parsed.password", "parsed.search", "parsed.hash"]) {
    assert.match(twilio, new RegExp(rejectedUrlPart.replace(".", "\\.")))
  }
  assert.match(twilio, /parsed\.pathname !== "\/"/)
  assert.match(twilio, /form\.append\("StatusCallbackEvent", event\)/)
  assert.doesNotMatch(twilio, /StatusCallbackEvent: "initiated ringing answered completed"/)
  assert.match(twilio, /use_inbound_webhook_on_number === false/)
  assert.match(twilio, /status >= 400 && status < 500 && status !== 408/)
  assert.match(twilio, /handler\.twilio\.com/)
  assert.match(twilio, /twiml\\\/EH\[0-9a-f\]/)
  assert.doesNotMatch(twilio, /host\.endsWith\("\.twilio\.com"\)/)
  assert.match(sms, /if \(!twilioSmsWebhookConfigured\(\)\)/)
  assert.match(sms, /let eventId = await recordEvent/)
  assert.doesNotMatch(sms, /inserted\[0\] \? await recordEvent/)
  assert.match(status, /if \(!twilioSmsWebhookConfigured\(\)\)/)
  assert.match(messages, /sms-status\?intent=\$\{messageId\}/)
  assert.match(messages, /twilio_sid = \$\{intentSid\}::text AND status = 'sending'/)
  assert.match(messages, /!receipt\.twilio_sid\.startsWith\("pending:"\)/)
  assert.match(outboundStatus, /twilio_sid = CASE WHEN twilio_sid LIKE 'pending:%'/)
  assert.match(outboundStatus, /kind = 'call\.out\.unknown'/)
  assert.match(call, /twilio_sid = \$\{pendingSid\}::text AND status = 'starting'/)
  assert.match(call, /!receipt\.twilio_sid\.startsWith\("pending:"\)/)
  for (const callbackBuilder of [messages, call, voice, outboundConnect, callTranscription]) {
    assert.match(callbackBuilder, /twilioCallbackUrl/)
    assert.doesNotMatch(callbackBuilder, /NEXT_PUBLIC_SITE_URL/)
  }
  assert.match(status, /id = \$\{intentId\}::bigint AND twilio_sid LIKE 'pending:%'/)
  assert.match(status, /twilio_sid = CASE WHEN twilio_sid LIKE 'pending:%'/)
  assert.match(status, /WHEN twilio_sid LIKE 'pending:%' AND \$\{status\}::text IN/)
  assert.match(status, /kind = 'sms\.delivery-unknown'/)
  assert.match(status, /read_at = COALESCE\(read_at, now\(\)\)/)
  assert.match(voice, /if \(!isConfiguredTwilioNumber\(to\)\) return twiml\("", 403\)/)
  assert.match(fallback, /isConfiguredTwilioNumber\(params\.get\("To"\) \?\? ""\)/)
  assert.doesNotMatch(recording, /recording_sid IS DISTINCT FROM/)
  assert.match(recording, /WHEN recording_sid = \$\{recordingSid\}::text THEN transcript_status/)
  assert.match(callTranscription, /AND transcript_status = 'submitting'/)
  assert.match(callTranscription, /\["ready", "empty"\]\.includes/)
  assert.match(leads, /WITH inserted_lead AS/)
  assert.match(leads, /captured_consent AS/)
  assert.match(leads, /'quote-consent:' \|\| inserted_lead\.public_id/)
  assert.match(health, /const shopBrainGateSatisfied = !shopBrainRequired \|\| shopBrainReady/)
  assert.match(health, /ready: shopBrainReady/)
  assert.match(health, /gateSatisfied: shopBrainGateSatisfied/)
})

test("provider readiness validates the Messaging Service outbound status callback", () => {
  const twilio = source("lib/twilio.ts")
  const health = source("app/api/health/route.ts")
  assert.match(twilio, /status_callback\?: string/)
  assert.match(twilio, /sameWebhookUrl\(service\?\.status_callback, twilioCallbackUrl\("\/api\/twilio\/sms-status"\)\)/)
  assert.match(twilio, /messagingStatusCallbackMatches/)
  assert.match(health, /twilioProvider\.messagingStatusCallbackMatches/)
  assert.match(health, /messagingStatusCallbackMatches: twilioProvider\.messagingStatusCallbackMatches/)
})

test("voice cutover and customer texting are independent launch gates", () => {
  const twilio = source("lib/twilio.ts")
  const phone = source("lib/shop-contact.ts")
  const workOrder = source("app/ops/leads/[id]/page.tsx")
  const customerPage = source("app/j/[token]/page.tsx")
  const health = source("app/api/health/route.ts")
  const login = source("app/ops/login-form.tsx")
  // C7: the /ops home is a redirect; the punch-card build lives on the install page.
  const jobs = source("app/ops/install/page.tsx")
  assert.match(twilio, /TWILIO_MESSAGING_SERVICE_SID/)
  assert.match(twilio, /TWILIO_PUBLIC_NUMBER_ENABLED/)
  assert.match(twilio, /TWILIO_SMS_ENABLED/)
  assert.match(twilio, /MessagingServiceSid: messagingServiceSid/)
  assert.doesNotMatch(twilio, /new URLSearchParams\(\{ To: input\.to, From:/)
  assert.match(phone, /voiceReady: publicNumberEnabled/)
  assert.match(phone, /textReady: publicNumberEnabled && twilioSmsConfigured\(\)/)
  assert.match(workOrder, /hasCustomerPhone && <TrackedCallButton/)
  assert.match(workOrder, /customerTextReady && <Link[^>]*href="#spike">Text<\/Link>/)
  assert.match(customerPage, /shopPhone\.textReady \? "Call or text us" : "Call the shop"/)
  assert.match(health, /publicNumberEnabled/)
  assert.match(health, /messagingServiceConfigured/)
  assert.match(health, /consentLedgerReady/)
  assert.match(health, /uploadRecoveryBacklog/)
  assert.match(login, /smsReady && \(!picked \|\| picked\.hasSms\)/)
  assert.match(jobs, /hasSms: smsReady && Boolean\(person\.cell_phone\)/)
})

test("every Jobs recorder follows the Deepgram and Blob readiness gate", () => {
  const readiness = source("lib/voice-transcription.ts")
  const capture = source("app/ops/voice-capture-button.tsx")
  const layout = source("app/ops/layout.tsx")
  const header = source("app/ops/ops-header.tsx")
  const more = source("app/ops/more-menu.tsx")
  const dock = source("app/ops/shop-dock.tsx")
  const newIntake = source("app/ops/intake/new/page.tsx")
  const callIntake = source("app/ops/intake/[draftId]/page.tsx")
  const intake = source("app/ops/intake/inline-job-intake.tsx")
  const workOrder = source("app/ops/leads/[id]/page.tsx")
  const done = source("app/ops/leads/[id]/done-stamp.tsx")
  const reply = source("app/ops/leads/[id]/spike-reply.tsx")

  assert.match(readiness, /DEEPGRAM_API_KEY/)
  assert.match(readiness, /BLOB_READ_WRITE_TOKEN/)
  assert.match(capture, /available: boolean/)
  assert.match(capture, /if \(!available\) return/)
  assert.match(capture, /if \(!available \|\| disabled \|\| transcribing/)
  assert.match(capture, /disabled=\{!available \|\| disabled \|\| transcribing\}/)
  assert.match(capture, /unavailableLabel = "Voice not set up"/)

  assert.match(layout, /voiceTranscriptionConfigured\(\)/)
  assert.match(layout, /<OpsCompactHeader[^>]*voiceReady=\{voiceReady\}/)
  assert.match(header, /<MoreMenu[^>]*voiceReady=\{voiceReady\}/)
  assert.match(more, /<ShopDock voiceReady=\{voiceReady\}/)
  assert.match(dock, /<VoiceCaptureButton available=\{voiceReady\}/)

  // C7: the /ops home redirects to /board, so the intake pages are the routes
  // that wire voice readiness; the layout gates the shared chrome above.
  for (const route of [newIntake, callIntake]) {
    assert.match(route, /voiceTranscriptionConfigured\(\)/)
    assert.match(route, /voiceReady=\{voiceTranscriptionConfigured\(\)\}/)
  }
  assert.match(workOrder, /const voiceReady = voiceTranscriptionConfigured\(\)/)
  assert.match(workOrder, /<DoneStamp[^>]*voiceReady=\{voiceReady\}/)
  assert.match(workOrder, /<SpikeReply[\s\S]*?voiceReady=\{voiceReady\}/)
  for (const consumer of [intake, done, reply]) assert.match(consumer, /available=\{voiceReady\}/)
  assert.match(done, /voiceReady && "speechSynthesis" in window/)
})

test("the install surface and manifest are scoped to private operations", () => {
  const manifest = source("app/ops/manifest.webmanifest/route.ts")
  const layout = source("app/ops/layout.tsx")
  const install = source("app/ops/install/page.tsx")
  const button = source("app/ops/install/install-app-button.tsx")
  const worker = source("app/ops/register-ops-service-worker.ts")
  const css = source("app/globals.css")
  assert.match(manifest, /name: "MCSW Jobs"/)
  assert.match(manifest, /short_name: "MCSW Jobs"/)
  assert.match(manifest, /display: "standalone"/)
  assert.match(manifest, /scope: "\/ops\/"/)
  assert.match(layout, /manifest: "\/ops\/manifest\.webmanifest"/)
  assert.match(worker, /register\("\/ops-sw\.js", \{ scope: "\/ops\/" \}\)/)
  assert.match(install, /getAuthenticatedOperator/)
  assert.match(install, /Install MCSW Jobs/)
  assert.match(install, /Install app/)
  assert.match(install, /Add to Home screen/)
  assert.match(button, /beforeinstallprompt/)
  assert.match(css, /\.ops-install-page > \.ops-page-heading\s*\{[^}]*display:\s*grid/s)
})

test("deprecated metaphors are absent from visible app labels", () => {
  const css = source("app/globals.css")
  const ui = [
    source("app/ops/page.tsx"),
    source("app/ops/ops-header.tsx"),
    source("app/ops/more-menu.tsx"),
    source("app/ops/shop-dock.tsx"),
    source("app/ops/wire-strip.tsx"),
    source("app/ops/login-form.tsx"),
    source("app/ops/leads/[id]/page.tsx"),
    source("app/j/[token]/page.tsx"),
    source("components/navbar.tsx"),
    source("components/mainstreet-menu.tsx"),
  ].map(visibleJsxText).join(" ")
  assert.doesNotMatch(ui, /The Works|The Wall|Needs You Now|The Wire|Receipt Cabinet|The Spike|Promise Rack|Promise Tags|Setup Jig|Command Bench|Story So Far|Source Ledger|Jobsite Radio|Regulars[’'] Rail|Slam DONE|Job Glass/i)
  assert.doesNotMatch(css, /content:\s*["']Pull["']/i)
  assert.match(ui, /MCSW Jobs/)
  assert.match(ui, /Customer Page/)
})

test("owner analytics guards financial queries and reports business totals without worker surveillance", () => {
  const analytics = source("lib/owner-analytics.ts")
  const page = source("app/ops/analytics/page.tsx")
  assert.ok(page.indexOf("getAuthenticatedOperator()") < page.indexOf('operator.role !== "owner"'))
  assert.ok(page.indexOf('operator.role !== "owner"') < page.indexOf("getOwnerAnalytics(operator.role"))
  assert.ok(analytics.indexOf('operatorRole !== "owner"') < analytics.indexOf("const sql = getSql()"))
  assert.match(analytics, /l\.is_test = false/g)
  assert.match(analytics, /\$\{anchor\}::timestamptz/)
  assert.match(analytics, /\$\{days\}::int/)
  assert.match(analytics, /percentile_cont\(0\.5::double precision\)/)
  assert.match(analytics, /revenue_cents/)
  assert.match(analytics, /paid_amount_cents/)
  assert.match(analytics, /invoice_total_cents/)
  assert.doesNotMatch(analytics, /assigned_operator|operator_id|JOIN operators/i)
  assert.match(page, /Business totals without crew rankings/)
  for (const range of [30, 90, 365]) assert.match(analytics, new RegExp(`\\b${range}\\b`))
})
